name: Git Workshop Demo

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'chore/**'
      - main

env:
  SERVER_IP: '127.0.0.1'
  SERVER_PORT: 80
  REPO_NAME: ${{ github.repository }}

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      COMPANY_NAME: 'NTPLC'
    environment: development
    steps:
      - run: echo "Hello ${{ github.actor }} Repo ${{ env.REPO_NAME }}"
      - run: echo ${{ env.SERVER_IP }}
      - run: echo ${{ env.SERVER_PORT}}
      - run: echo ${{ env.COMPANY_NAME }}
      - run: echo ${{ vars.APP_NAME }}
      - run: echo ${{ secrets.API_KEY }}

  job-2:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Server IP -> ${{ env.SERVER_IP }}"
      - run: echo "${{ vars.APP_NAME }}"